platform: linux

image_resource:
  type: mock
  source: {mirror_self: true}

params:
  EXPECTED_EXIT_CODE:

run:
  path: sh
  args:
  - -c
  - |
    set -x

    nslookup web
    if [ $? -ne $EXPECTED_EXIT_CODE ]; then
      exit 1
    fi
